### ISSUE TITLE
array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead

### ISSUE THREAD

**Issue by rostockahoi** [voku/php-domain-parser#5]
PHP version: 7.4.4

There is a deprecation warning regarding the usage of `array_key_exists()` in `src/Pdp/Parser.php`. In my case (Laravel) this leads to a 500 error.

I worked around this issue by changing the function call from
```
\array_key_exists($part, $publicSuffixList);
```
to
```
\array_key_exists($part, $publicSuffixList->getArrayCopy());
```
in lines 159, 166 and 172.

However, I don't know whether this works in PHP versions prior to 7.4. I also don't know what performance implications this implementation would have using a copy of that array.

Should I provide a PR for this?

**Comment by voku** [comment]
Thanks for the bug report, fixed in version 8.0.1
